/**
 * SXK-DEV　森心康分龄发展量表
 *
 * 由 `scripts/t2-extract-toolkit.ts` 從 `NEWT2/森心康评估工具包_20260908.zip` 產生，**請勿手改** —— 改了下一次重跑就會被蓋掉，
 * 而且 `test/toolkit.structure.test.ts` 會比對這一份與腳本重跑的結果。
 * 來源檔：`01_综合筛查与官方工具/森心康分龄发展量表_SXK-DEV.html`（sha256 1b091a0c8f6f…）。
 * 分段只抄報告那一套（＝紙本「分數解讀」），`postMessage` 與中控台的兩套一個數字都沒有。
 */

import type { ToolkitBank } from './types';

export const SXK_DEV: ToolkitBank = {
  id: 'sxk-dev',
  code: 'SXK-DEV',
  title: '森心康分龄发展量表',
  source: { file: '01_综合筛查与官方工具/森心康分龄发展量表_SXK-DEV.html', sha256: '1b091a0c8f6f626a9906603ad37acaa542bcd7f26642bd6b79ae6fe8a521d921' },
  options: [
    { value: 'pass', label: '通过' },
    { value: 'fail', label: '未通过' },
    { value: 'skip', label: '不评' },
  ],
  sections: [
    {
      key: 'MOT',
      name: '粗大动作',
      ageBand: { key: '0-6', lo: 0, hi: 6 },
      items: [
        { no: 1, text: '趴着时能抬起头并短暂撑住', startMonth: null },
        { no: 2, text: '被抱起时头能自己稳住不后仰', startMonth: null },
        { no: 3, text: '仰躺时会踢腿、挥动双手', startMonth: null },
        { no: 4, text: '能从仰躺翻成侧躺', startMonth: null },
        { no: 5, text: '被抱直立时腿会短暂用力踩', startMonth: null },
      ],
    },
    {
      key: 'FM',
      name: '精细动作',
      ageBand: { key: '0-6', lo: 0, hi: 6 },
      items: [
        { no: 1, text: '手会张开，不总是握拳', startMonth: null },
        { no: 2, text: '会把手放进嘴里', startMonth: null },
        { no: 3, text: '看到东西会伸手去碰', startMonth: null },
        { no: 4, text: '能短暂抓住放进手心的小物', startMonth: null },
        { no: 5, text: '两手会在胸前相碰', startMonth: null },
      ],
    },
    {
      key: 'LANG',
      name: '语言',
      ageBand: { key: '0-6', lo: 0, hi: 6 },
      items: [
        { no: 1, text: '听到声音会转头找', startMonth: null },
        { no: 2, text: '会发出咕咕声或啊啊声', startMonth: null },
        { no: 3, text: '被逗弄时会出声回应', startMonth: null },
        { no: 4, text: '哭声有不同（饿、困、不舒服听得出来）', startMonth: null },
        { no: 5, text: '安静时会自己发声玩', startMonth: null },
      ],
    },
    {
      key: 'SOC',
      name: '社交',
      ageBand: { key: '0-6', lo: 0, hi: 6 },
      items: [
        { no: 1, text: '会注视大人的脸', startMonth: null },
        { no: 2, text: '被逗时会露出笑容', startMonth: null },
        { no: 3, text: '喜欢有人陪、被抱起会安静下来', startMonth: null },
        { no: 4, text: '会用眼神跟着走动的人', startMonth: null },
        { no: 5, text: '被抱时会调整姿势贴合大人', startMonth: null },
      ],
    },
    {
      key: 'ADL',
      name: '生活自理',
      ageBand: { key: '0-6', lo: 0, hi: 6 },
      items: [
        { no: 1, text: '吃奶时吸吮有力、能持续', startMonth: null },
        { no: 2, text: '喝完后能安稳一段时间', startMonth: null },
        { no: 3, text: '作息逐渐规律（醒睡有节奏）', startMonth: null },
        { no: 4, text: '吃奶时会用手扶着', startMonth: null },
        { no: 5, text: '醒着时能安静观察周围', startMonth: null },
      ],
    },
    {
      key: 'COG',
      name: '认知',
      ageBand: { key: '0-6', lo: 0, hi: 6 },
      items: [
        { no: 1, text: '眼睛能盯着移动的东西看', startMonth: null },
        { no: 2, text: '对突然的声音有反应', startMonth: null },
        { no: 3, text: '会重复做让自己开心的动作', startMonth: null },
        { no: 4, text: '对熟悉的声音会安静下来', startMonth: null },
        { no: 5, text: '会区分白天与夜晚的作息', startMonth: null },
      ],
    },
    {
      key: 'MOT',
      name: '粗大动作',
      ageBand: { key: '7-12', lo: 7, hi: 12 },
      items: [
        { no: 1, text: '能自己坐稳一小段时间', startMonth: null },
        { no: 2, text: '会翻身（仰翻趴、趴翻仰都行）', startMonth: null },
        { no: 3, text: '扶着东西能站起来', startMonth: null },
        { no: 4, text: '会爬或用其他方式移动身体', startMonth: null },
        { no: 5, text: '能扶着家具横向移动', startMonth: null },
      ],
    },
    {
      key: 'FM',
      name: '精细动作',
      ageBand: { key: '7-12', lo: 7, hi: 12 },
      items: [
        { no: 1, text: '能用拇指和食指捏起小东西', startMonth: null },
        { no: 2, text: '会把东西从一只手换到另一只手', startMonth: null },
        { no: 3, text: '会敲打、摇晃手上的玩具', startMonth: null },
        { no: 4, text: '会把东西放进容器里', startMonth: null },
        { no: 5, text: '会用食指戳或指', startMonth: null },
      ],
    },
    {
      key: 'LANG',
      name: '语言',
      ageBand: { key: '7-12', lo: 7, hi: 12 },
      items: [
        { no: 1, text: '叫他名字会回头', startMonth: null },
        { no: 2, text: '会发出「爸爸」「妈妈」这类连续音', startMonth: null },
        { no: 3, text: '听到「不可以」会停下来', startMonth: null },
        { no: 4, text: '会用手势表达（指、挥手）', startMonth: null },
        { no: 5, text: '会模仿大人的语调', startMonth: null },
      ],
    },
    {
      key: 'SOC',
      name: '社交',
      ageBand: { key: '7-12', lo: 7, hi: 12 },
      items: [
        { no: 1, text: '会认得熟悉的人、对陌生人警觉', startMonth: null },
        { no: 2, text: '会主动伸手要抱', startMonth: null },
        { no: 3, text: '玩躲猫猫会有反应', startMonth: null },
        { no: 4, text: '会看大人的表情决定要不要做', startMonth: null },
        { no: 5, text: '会主动把东西递给大人', startMonth: null },
      ],
    },
    {
      key: 'ADL',
      name: '生活自理',
      ageBand: { key: '7-12', lo: 7, hi: 12 },
      items: [
        { no: 1, text: '能自己拿着食物送进嘴里', startMonth: null },
        { no: 2, text: '喝水时会配合杯子', startMonth: null },
        { no: 3, text: '穿衣时会配合伸手伸脚', startMonth: null },
        { no: 4, text: '会自己拿饼干咬', startMonth: null },
        { no: 5, text: '换尿布时会配合抬腿', startMonth: null },
      ],
    },
    {
      key: 'COG',
      name: '认知',
      ageBand: { key: '7-12', lo: 7, hi: 12 },
      items: [
        { no: 1, text: '东西被藏起来会去找', startMonth: null },
        { no: 2, text: '会模仿简单动作（拍手、再见）', startMonth: null },
        { no: 3, text: '对因果玩具有兴趣（按了会响）', startMonth: null },
        { no: 4, text: '会把盖子打开找里面的东西', startMonth: null },
        { no: 5, text: '知道某些东西掉下去会有声音', startMonth: null },
      ],
    },
    {
      key: 'MOT',
      name: '粗大动作',
      ageBand: { key: '13-24', lo: 13, hi: 24 },
      items: [
        { no: 1, text: '能自己走稳', startMonth: null },
        { no: 2, text: '会蹲下捡东西再站起来', startMonth: null },
        { no: 3, text: '扶着能上下楼梯', startMonth: null },
        { no: 4, text: '会踢球或丢球', startMonth: null },
        { no: 5, text: '会推或拉着玩具走', startMonth: null },
      ],
    },
    {
      key: 'FM',
      name: '精细动作',
      ageBand: { key: '13-24', lo: 13, hi: 24 },
      items: [
        { no: 1, text: '会自己拿笔涂鸦', startMonth: null },
        { no: 2, text: '能叠起两三块积木', startMonth: null },
        { no: 3, text: '会翻书页', startMonth: null },
        { no: 4, text: '会把小东西放进小口容器', startMonth: null },
        { no: 5, text: '会把小球投进洞里', startMonth: null },
      ],
    },
    {
      key: 'LANG',
      name: '语言',
      ageBand: { key: '13-24', lo: 13, hi: 24 },
      items: [
        { no: 1, text: '会说十个以上有意义的词', startMonth: null },
        { no: 2, text: '听得懂简单指令（把球给我）', startMonth: null },
        { no: 3, text: '会用词表达需求（要、不要）', startMonth: null },
        { no: 4, text: '会指认身体部位或图片', startMonth: null },
        { no: 5, text: '会摇头或点头表示要不要', startMonth: null },
      ],
    },
    {
      key: 'SOC',
      name: '社交',
      ageBand: { key: '13-24', lo: 13, hi: 24 },
      items: [
        { no: 1, text: '会模仿大人做家事', startMonth: null },
        { no: 2, text: '对同龄孩子有兴趣、会靠近看', startMonth: null },
        { no: 3, text: '会用眼神或声音引起大人注意', startMonth: null },
        { no: 4, text: '分离时会有情绪，回来能安抚', startMonth: null },
        { no: 5, text: '会指给大人看有趣的东西', startMonth: null },
      ],
    },
    {
      key: 'ADL',
      name: '生活自理',
      ageBand: { key: '13-24', lo: 13, hi: 24 },
      items: [
        { no: 1, text: '会自己用汤匙吃（会洒也算）', startMonth: null },
        { no: 2, text: '会自己拿杯子喝水', startMonth: null },
        { no: 3, text: '脱袜子、脱帽子会自己来', startMonth: null },
        { no: 4, text: '大小便前后会有表示', startMonth: null },
        { no: 5, text: '会自己脱鞋', startMonth: null },
      ],
    },
    {
      key: 'COG',
      name: '认知',
      ageBand: { key: '13-24', lo: 13, hi: 24 },
      items: [
        { no: 1, text: '会假装玩（喂娃娃、开玩具车）', startMonth: null },
        { no: 2, text: '会配对相同的东西', startMonth: null },
        { no: 3, text: '知道常见物品的用途（梳子、电话）', startMonth: null },
        { no: 4, text: '会用工具拿到构不到的东西', startMonth: null },
        { no: 5, text: '认得镜子里的自己', startMonth: null },
      ],
    },
    {
      key: 'MOT',
      name: '粗大动作',
      ageBand: { key: '25-36', lo: 25, hi: 36 },
      items: [
        { no: 1, text: '能双脚同时离地跳', startMonth: null },
        { no: 2, text: '会自己上下楼梯（可扶）', startMonth: null },
        { no: 3, text: '能单脚站一两秒', startMonth: null },
        { no: 4, text: '会跑，方向能控制', startMonth: null },
        { no: 5, text: '会用脚踢固定的球', startMonth: null },
      ],
    },
    {
      key: 'FM',
      name: '精细动作',
      ageBand: { key: '25-36', lo: 25, hi: 36 },
      items: [
        { no: 1, text: '会照着画直线或圆圈', startMonth: null },
        { no: 2, text: '能叠六块以上积木', startMonth: null },
        { no: 3, text: '会转开瓶盖', startMonth: null },
        { no: 4, text: '会用剪刀剪（剪得开就算）', startMonth: null },
        { no: 5, text: '会把珠子串起来', startMonth: null },
      ],
    },
    {
      key: 'LANG',
      name: '语言',
      ageBand: { key: '25-36', lo: 25, hi: 36 },
      items: [
        { no: 1, text: '会说两三个词组成的句子', startMonth: null },
        { no: 2, text: '听得懂两步骤指令', startMonth: null },
        { no: 3, text: '会问「这是什么」', startMonth: null },
        { no: 4, text: '别人大致听得懂他说的话', startMonth: null },
        { no: 5, text: '会跟着唱简单儿歌或念谣', startMonth: null },
      ],
    },
    {
      key: 'SOC',
      name: '社交',
      ageBand: { key: '25-36', lo: 25, hi: 36 },
      items: [
        { no: 1, text: '会和其他孩子在同一空间各玩各的', startMonth: null },
        { no: 2, text: '会说自己的名字', startMonth: null },
        { no: 3, text: '会表达简单情绪（生气、开心）', startMonth: null },
        { no: 4, text: '会等一下下（短暂等待）', startMonth: null },
        { no: 5, text: '会说「我的」表示所有权', startMonth: null },
      ],
    },
    {
      key: 'ADL',
      name: '生活自理',
      ageBand: { key: '25-36', lo: 25, hi: 36 },
      items: [
        { no: 1, text: '白天大小便能自己表示', startMonth: null },
        { no: 2, text: '会自己脱简单衣物', startMonth: null },
        { no: 3, text: '洗手会自己搓', startMonth: null },
        { no: 4, text: '吃饭大致能自己完成', startMonth: null },
        { no: 5, text: '会自己开水龙头洗手', startMonth: null },
      ],
    },
    {
      key: 'COG',
      name: '认知',
      ageBand: { key: '25-36', lo: 25, hi: 36 },
      items: [
        { no: 1, text: '会依颜色或形状分类', startMonth: null },
        { no: 2, text: '懂得「大／小」「多／少」', startMonth: null },
        { no: 3, text: '会照顺序做两件事', startMonth: null },
        { no: 4, text: '懂得「一个」和「很多」', startMonth: null },
        { no: 5, text: '会照样排出简单顺序', startMonth: null },
      ],
    },
    {
      key: 'MOT',
      name: '粗大动作',
      ageBand: { key: '37-48', lo: 37, hi: 48 },
      items: [
        { no: 1, text: '能单脚站三秒以上', startMonth: null },
        { no: 2, text: '会双脚交替上楼梯', startMonth: null },
        { no: 3, text: '会骑三轮车或滑步车', startMonth: null },
        { no: 4, text: '能接住抛来的大球', startMonth: null },
        { no: 5, text: '会侧向或倒退走', startMonth: null },
      ],
    },
    {
      key: 'FM',
      name: '精细动作',
      ageBand: { key: '37-48', lo: 37, hi: 48 },
      items: [
        { no: 1, text: '会画十字或方形', startMonth: null },
        { no: 2, text: '会自己扣大钮扣', startMonth: null },
        { no: 3, text: '会用剪刀沿线剪', startMonth: null },
        { no: 4, text: '握笔姿势较稳定', startMonth: null },
        { no: 5, text: '会照样折纸一次', startMonth: null },
      ],
    },
    {
      key: 'LANG',
      name: '语言',
      ageBand: { key: '37-48', lo: 37, hi: 48 },
      items: [
        { no: 1, text: '会说四五个词的句子', startMonth: null },
        { no: 2, text: '会讲刚发生的事', startMonth: null },
        { no: 3, text: '会用「为什么」提问', startMonth: null },
        { no: 4, text: '陌生人大致听得懂他说话', startMonth: null },
        { no: 5, text: '会用「和」「跟」连接两件事', startMonth: null },
      ],
    },
    {
      key: 'SOC',
      name: '社交',
      ageBand: { key: '37-48', lo: 37, hi: 48 },
      items: [
        { no: 1, text: '会和其他孩子一起玩、有互动', startMonth: null },
        { no: 2, text: '会轮流（可能需提醒）', startMonth: null },
        { no: 3, text: '会表达喜欢谁、不喜欢什么', startMonth: null },
        { no: 4, text: '会遵守简单规则', startMonth: null },
        { no: 5, text: '会说出朋友的名字', startMonth: null },
      ],
    },
    {
      key: 'ADL',
      name: '生活自理',
      ageBand: { key: '37-48', lo: 37, hi: 48 },
      items: [
        { no: 1, text: '能自己穿脱大部分衣物', startMonth: null },
        { no: 2, text: '会自己上厕所（可能需协助擦拭）', startMonth: null },
        { no: 3, text: '吃饭能自己完成不需喂', startMonth: null },
        { no: 4, text: '会自己刷牙（需检查）', startMonth: null },
        { no: 5, text: '会自己倒水喝', startMonth: null },
      ],
    },
    {
      key: 'COG',
      name: '认知',
      ageBand: { key: '37-48', lo: 37, hi: 48 },
      items: [
        { no: 1, text: '会数到十', startMonth: null },
        { no: 2, text: '认得基本颜色', startMonth: null },
        { no: 3, text: '懂「上面／下面」「前面／后面」', startMonth: null },
        { no: 4, text: '会拼简单拼图（六片以上）', startMonth: null },
        { no: 5, text: '会说出物品的用途', startMonth: null },
      ],
    },
    {
      key: 'MOT',
      name: '粗大动作',
      ageBand: { key: '49-72', lo: 49, hi: 72 },
      items: [
        { no: 1, text: '能单脚站五秒以上', startMonth: null },
        { no: 2, text: '会单脚连续跳', startMonth: null },
        { no: 3, text: '会跳绳或类似协调动作', startMonth: null },
        { no: 4, text: '能踢准目标', startMonth: null },
        { no: 5, text: '会拍球连续三次以上', startMonth: null },
      ],
    },
    {
      key: 'FM',
      name: '精细动作',
      ageBand: { key: '49-72', lo: 49, hi: 72 },
      items: [
        { no: 1, text: '会写自己的名字或部分笔画', startMonth: null },
        { no: 2, text: '会照样画三角形', startMonth: null },
        { no: 3, text: '会自己绑鞋带或打结', startMonth: null },
        { no: 4, text: '剪贴作品能大致完成', startMonth: null },
        { no: 5, text: '会照样画人（头、身体、四肢）', startMonth: null },
      ],
    },
    {
      key: 'LANG',
      name: '语言',
      ageBand: { key: '49-72', lo: 49, hi: 72 },
      items: [
        { no: 1, text: '能完整讲一件事的经过', startMonth: null },
        { no: 2, text: '会用「因为／所以」', startMonth: null },
        { no: 3, text: '会说出反义词', startMonth: null },
        { no: 4, text: '听得懂三步骤指令', startMonth: null },
        { no: 5, text: '会解释游戏规则给别人听', startMonth: null },
      ],
    },
    {
      key: 'SOC',
      name: '社交',
      ageBand: { key: '49-72', lo: 49, hi: 72 },
      items: [
        { no: 1, text: '能和同伴合作完成一件事', startMonth: null },
        { no: 2, text: '会安慰或帮助别人', startMonth: null },
        { no: 3, text: '输了游戏能大致接受', startMonth: null },
        { no: 4, text: '能在团体中遵守规则', startMonth: null },
        { no: 5, text: '能主动邀请别人一起玩', startMonth: null },
      ],
    },
    {
      key: 'ADL',
      name: '生活自理',
      ageBand: { key: '49-72', lo: 49, hi: 72 },
      items: [
        { no: 1, text: '能完全自己穿脱衣鞋', startMonth: null },
        { no: 2, text: '上厕所能全程自理', startMonth: null },
        { no: 3, text: '会自己收拾玩具', startMonth: null },
        { no: 4, text: '会看情况添减衣服', startMonth: null },
        { no: 5, text: '会自己准备简单的点心', startMonth: null },
      ],
    },
    {
      key: 'COG',
      name: '认知',
      ageBand: { key: '49-72', lo: 49, hi: 72 },
      items: [
        { no: 1, text: '会数到二十以上', startMonth: null },
        { no: 2, text: '认得数字或部分字', startMonth: null },
        { no: 3, text: '能比较大小、长短', startMonth: null },
        { no: 4, text: '会说出简单的解决办法', startMonth: null },
        { no: 5, text: '懂得左右', startMonth: null },
      ],
    },
  ],
  tiers: [
    { tier: 1, key: '达成良好', min: 90 },
    { tier: 2, key: '大致达成', min: 75, max: 89 },
    { tier: 3, key: '部分未达成', min: 60, max: 74 },
    { tier: 4, key: '明显落后', min: 0, max: 59 },
  ],
  preQuestions: [],
};
